# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dbe00b1a16226f54e56f866b31cdbfe801daedd899b7522a6e3838c953655830bbe81399bf402445432f9fc108c68a10363fbbcdedfbe34f68832f57f52a033

test:
  secret_key_base: b7e8a4be9449a1aa6b3c0b2eb909c936648bd560fad3ad4b19d95af5544e373c89f3aa2655f97e453ad4bc8c467c21e27d40a139f6e41f3dd15457aa8308ea59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
